version: "3"
services:
  app:
#    image: davegarred/woodinville
    build: .
    ports:
      - "8000:8000"
#    links:
#      - db

#  db:
#    restart: always
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=demouser
#      - POSTGRES_PASSWORD=demopass
#      - POSTGRES_DB=postgres